name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-check:
    name: runner / mypy (github-check)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: mypy-github-check
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: warning
          reviewdog_flags: -filter-mode=file -fail-on-error
          workdir: ./testdata/

  test-pr-check:
    if: github.event_name == 'pull_request'
    name: runner / mypy (github-pr-check)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: mypy-github-pr-check
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: warning
          reviewdog_flags: -filter-mode=file -fail-on-error
          workdir: ./testdata/

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / mypy (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: mypy-github-pr-review
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          reviewdog_flags: -filter-mode=file -fail-on-error
          workdir: ./testdata/
